# N.B. revisit makefiles and requirements.txt files when updating.
# In particular, we are "unpinning" (making >= instead of ==) their dependencies.
{% extends "base.yaml" %}

{% block recipe %}

package:
  name: aeon
  version: {{ aeon_version }}

source:
  fn: aeon-v{{ aeon_version }}.tar.gz
  url: https://github.com/NervanaSystems/aeon/archive/v{{ aeon_version }}.tar.gz
  sha256: 38228b865d717922bd0469e622c8ad98d02f2e846656e23b4b253b7167450d0d

build:
  number: 1
  skip: true  # [not linux]
  features:
    - blas_{{ blas_variant }}
    - cuda{{ cuda_version }}
    - aeon_cuda{{ cuda_version }}
  script:
    - HAS_GPU=1 python setup.py install
    # N.B. aeon does not use setuptools

requirements:

  build:
    - python

    # Build only deps
    - pkg-config
    - clangdev
    - cmake
    - ninja

    # We are not building docs; these will get pip installed but we do not care
    # - breathe >=4.2.0  # Currently we would need to rerender to get a 3.6 package
    # - flask

    # Runtimes
    - numpy x.x
    - blas 1.1 {{ blas_variant }}
    - openblas 0.2.19|0.2.19.*
    - sox
    - opencv 3.*
    - pillow >=3.3.1

  run:
    - python
    - numpy x.x
    - sox
    - opencv 3.*
    - pillow >=3.3.1
    - blas 1.1 {{ blas_variant }}
    - openblas 0.2.19|0.2.19.*

test:
  source_files:
    - test
  requires:
    - aeon-cuda-feature {{ aeon_cuda_version }}
    - cuda-feature {{ cuda_version }}
    - pytest >=3.0.1
    - pytest-cov >=2.3.1
  imports:
    - aeon
  commands:
    - py.test test

about:
  home: https://github.com/NervanaSystems/aeon
  license: Apache 2
  license_file: LICENSE
  summary: module for data loading and transforming http://aeon.nervanasys.com

{% endblock %}
